name: auto_create_pr_for_data

on: push

jobs:
  fetch_data:
    runs-on: ubuntu-18.04
    steps:
      - name: Setting Git
        run: |
          git config --global user.name github-actions
          git config --global user.email actions@github.com

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: build docker image
        run: |
          docker-compose build fetch_shimane_data

      - name: Crawler start
        id: genjson
        run: |
          docker-compose run fetch_shimane_data

          if [ -z "$(git status --porcelain)" ]; then
            echo "##[set-output name=changed;]false"
          else
            echo "##[set-output name=changed;]true"
          fi

      - name: Create pull request
        id: cpr
        if: steps.genjson.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.SuperSecret }}
          commit-message: BOT; UPDATE DATA
          title: BOT; UPDATE DATE
          reviewers: TaigaMikami
          path: shimane
          base: shimane
          branch: bot/update-data
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
